name: 'Tests'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Unit Testing
        run: docker compose run --rm tests
